name: Publish Application on GitHub Pages

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-web:
    name: Build Kotlin/Wasm
    runs-on: ubuntu-latest
    steps:
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: checkout code
        uses: actions/checkout@v4

      - name: run gradle tasks
        run: ./gradlew :webApp:jsBrowserDistribution

      - name: fix permissions
        run: chmod -R 0755 "webApp/build/dist/js/productionExecutable/"

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webApp/build/dist/js/productionExecutable/

  deploy:
    needs: build-web
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4